routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//tampilan login


//login
Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['namespace' => 'Auth' ,'as' => 'auth.'], function() {
	Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    // Route::post('register', 'RegisterController@register')->name('register');
    Route::post('logout', 'LoginController@logout')->name('logout');   
});     

//route untuk menampilkan dashboard
Route::get('awal', function () {
    return view('index');
});

//route untuk menampilkan help
Route::get('help', function () {
    return view('help.help');
});
Route::get('konten', function () {
    return view('help.konten');
});
Route::get('remedis', function () {
    return view('help.redis');
});
Route::get('adminhelp', function () {
    return view('help.admin');
});
Route::get('bidanhelp', function () {
    return view('help.bidan');
});
Route::get('pasienhelp', function () {
    return view('help.pasien');
});

//route content
 Route::get('content', 'Content\Controller\ContentController@index')->name('content.list');
 Route::get('content/add', 'Content\Controller\ContentController@create')->name('content.add');
 Route::post('content/create', 'Content\Controller\ContentController@store')->name('content.insert');
 Route::get('content/show/{id}', 'Content\Controller\ContentController@show')->name('content.show');
 Route::get('content/edit/{id}', 'Content\Controller\ContentController@edit')->name('content.edit');
 Route::post('content/update/{id}', 'Content\Controller\ContentController@update')->name('content.update');
 Route::get('content/delete/{id}', 'Content\Controller\ContentController@destroy')->name('content.delete');
 
//route CRUD admin
Route::get('admin', 'Admin\Controller\AdminController@index')->name('admin.list');
Route::get('admin/add', 'Admin\Controller\AdminController@create')->name('admin.add');
Route::post('admin/create', 'Admin\Controller\AdminController@store')->name('admin.insert');
Route::get('admin/show/{id}', 'Admin\Controller\AdminController@show')->name('admin.show');
Route::get('admin/edit/{id}', 'Admin\Controller\AdminController@edit')->name('admin.edit');
Route::post('admin/update/{id}', 'Admin\Controller\AdminController@update')->name('admin.update');
Route::get('admin/delete/{id}', 'Admin\Controller\AdminController@destroy')->name('admin.delete');

//route CRUD admin
Route::get('bidan', 'Bidan\Controller\BidanController@index')->name('bidan.list');
Route::get('bidan/add', 'Bidan\Controller\BidanController@create')->name('bidan.add');
Route::post('bidan/create', 'Bidan\Controller\BidanController@store')->name('bidan.insert');
Route::get('bidan/show/{id}', 'Bidan\Controller\BidanController@show')->name('bidan.show');
Route::get('bidan/edit/{id}', 'Bidan\Controller\BidanController@edit')->name('bidan.edit');
Route::post('bidan/update/{id}', 'Bidan\Controller\BidanController@update')->name('bidan.update');
Route::get('bidan/delete/{id}', 'Bidan\Controller\BidanController@destroy')->name('bidan.delete');

//route CRUD pasien
Route::get('pasien', 'Pasien\Controller\PasienController@index')->name('pasien.list');
Route::get('pasien/add', 'Pasien\Controller\PasienController@create')->name('pasien.add');
Route::post('pasien/create', 'Pasien\Controller\PasienController@store')->name('pasien.insert');
Route::get('pasien/show/{id}', 'Pasien\Controller\PasienController@show')->name('pasien.show');
Route::get('pasien/edit/{id}', 'Pasien\Controller\PasienController@edit')->name('pasien.edit');
Route::post('pasien/update/{id}', 'Pasien\Controller\PasienController@update')->name('pasien.update');
Route::get('pasien/delete/{id}', 'Pasien\Controller\PasienController@destroy')->name('pasien.delete');

//route CRUD redis pasien
Route::get('redis', 'Redis\Controller\RedisController@index')->name('redis.list');
Route::get('redis/add', 'Redis\Controller\RedisController@create')->name('redis.add');
Route::post('redis/create', 'Redis\Controller\RedisController@store')->name('redis.insert');
Route::get('redis/show/{id}', 'Redis\Controller\RedisController@show')->name('redis.show');
Route::get('redis/edit/{id}', 'Redis\Controller\RedisController@edit')->name('redis.edit');
Route::post('redis/update/{id}', 'Redis\Controller\RedisController@update')->name('redis.update');
Route::get('redis/delete/{id}', 'Redis\Controller\RedisController@destroy')->name('redis.delete');

//route CRUD data training
Route::get('training', 'Training\Controller\TrainingController@index')->name('training.list');
Route::get('training/add', 'Training\Controller\TrainingController@create')->name('training.add');
Route::post('training/create', 'Training\Controller\TrainingController@store')->name('training.insert');
Route::get('training/show/{id}', 'Training\Controller\TrainingController@show')->name('training.show');
Route::get('training/edit/{id}', 'Training\Controller\TrainingController@edit')->name('training.edit');
Route::post('training/update/{id}', 'Training\Controller\TrainingController@update')->name('training.update');
Route::get('training/delete/{id}', 'Training\Controller\TrainingController@destroy')->name('training.delete');

resources/views/admin.blade.php
@extends('index')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{url('/awal')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Management Users Admin</li>
      </ol>
      <br>
      <a class="nav-link" data-toggle="modal" data-target="#exampleModal"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Insert Konten</button></a>
      <br><br>
      <div class="card mb-3">
      	<div class="card-header">
          	<i class="fa fa-sticky-note"></i> Management Users Admin
      	</div>
        <div class="card-body">
        	<div class="table-responsive">
        		<table class="table table-striped" width="100%" cellspacing="0">
        	    	<thead>
        	      		<tr>
        	        		<th>Name</th>
        	        		<th>Position</th>
        	        		<th colspan="3">Office</th>
        	        		<th>Date of Publish</th>
        	        		<th><center>Action</center></th>
        	      		</tr>
        	    	</thead>
        	    	<tbody>
        				<tr>
        					<td>Tiger Nixon</td>
        					<td>System Architect</td>
        					<td>Edinburgh</td>
        					<td>Edinburgh</td>
        					<td>Edinburgh</td>
        					<td>22 March 2018</td>
        					<td>
        						<center>
        							<button type="button" class="btn btn-success btn-sm"><i class="fa fa-eye"></i> Show</button>
        							<button type="button" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> Edit</button>
        							<button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</button>
        						</center>
        					</td>
        				</tr>    	
        	    	</tbody>
        	  	</table>
        	 </div>
        </div>
      </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts/layouts')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
		<!-- Breadcrumbs-->
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="#">Beranda</a>
			</li>
		</ol>
		<p align="center"><img width="600" height="400" src="{{url('public/assets/images/admin.gif')}}"></p>
      	<p align="center">Selamat Datang di bagian Administrator </p>
    </div>
</div>
@endsection

resources/views/layouts.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Skripsi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- Bootstrap core CSS-->
    <link rel="stylesheet" type="text/css" href="{{url('public/asset/vendor/bootstrap/css/bootstrap.min.css')}}" />
    <!-- Custom fonts for this template-->
    <link rel="stylesheet" type="text/css" href="{{url('public/asset/vendor/font-awesome/css/font-awesome.min.css')}}" />
    <!-- Page level plugin CSS-->
    <link rel="stylesheet" type="text/css" href="{{url('public/asset/datatables/dataTables.bootstrap4.css')}}">
    <!-- Custom styles for this template-->
    <link rel="stylesheet" type="text/css" href="{{url('public/asset/css/sb-admin.css')}}">
    <script src="main.js"></script>

</head>
  <!-- Navigation-->
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="index.html">Admin</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ url('/awal') }}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{ url('/content') }}">
            <i class="fa fa-fw fa-table"></i>
            <span class="nav-link-text">Management Content</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-sitemap"></i>
            <span class="nav-link-text">Management User</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li>
              <a href="{{ url('/admin') }}">Admin</a>
            </li>
            <li>
              <a href="{{ url('/bidan') }}">Bidan</a>
            </li>
            <li>
              <a href="{{ url('/user') }}">User</a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
          <a class="nav-link" href="{{ url('/help') }}">
            <i class="fa fa-fw fa-link"></i>
            <span class="nav-link-text">Help</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>

  <!--CONTENT-->
  @yield('content')

</body>
</html>

    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{{ route('auth.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
            <form id="logout-form" action="{{ route('auth.logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{{url('public/asset/vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{url('public/asset/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{{url('public/asset/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{{url('public/asset/vendor/chart.js/Chart.min.js')}}"></script>
    <script src="{{url('public/asset/vendor/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{url('public/asset/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{{url('public/asset/js/sb-admin.min.js')}}"></script>
    <!-- Custom scripts for this page-->
    <script src="{{url('public/asset/js/sb-admin-datatables.min.js')}}"></script>
    <script src="{{url('public/asset/js/sb-admin-charts.min.js')}}"></script>